apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentiment-analysis
  labels:
    app: sentiment-analysis
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sentiment-analysis
  template:
    metadata:
      labels:
        app: sentiment-analysis
    spec:
      containers:
      - name: sentiment-analysis
        image: avnishsingh17/sentiment-analysis:v1
        ports:
        - containerPort: 8000
        resources:
          limits:
            memory: "8Gi"
            cpu: "6"
            nvidia.com/gpu: 1  # Request 1 GPU
          requests:
            memory: "5Gi"
            cpu: "4"
            nvidia.com/gpu: 1  # Request 1 GPU
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 35
          periodSeconds: 15
        env:
        - name: LOG_LEVEL
          value: "info"
      imagePullSecrets:
      - name: regcred