apiVersion: v1
kind: Service
metadata:
  name: sentiment-analysis-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8000"
    prometheus.io/path: "/metrics"
spec:
  selector:
    app: sentiment-analysis
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: NodePort